### ISSUE TITLE
Left/right Panels are incorrectly expanded

### ISSUE THREAD

**Issue by fossfreedom** [tarkah/budgie-cputemp-applet#3]
![image](https://user-images.githubusercontent.com/996240/121787491-2f234f00-cbbe-11eb-9ddd-d18fd0c80f8a.png)

For left or right panels the panel size is expanded since the applet orientation / text is too wide.

Suggest either change the orientation or make the temperature part appear below the icon.

**Comment by tarkah** [comment]
Ahh, nice catch. I'll play around with a few options to make sure it looks good with vertical panels.

**Comment by tarkah** [comment]
@fossfreedom I've fixed this by setting the container to vertical layout and using smaller text when left / right panel is used / switched to.

![image](https://user-images.githubusercontent.com/10239377/122817736-26e9a480-d28d-11eb-8b33-8db24d7b6eaa.png)
