### ISSUE TITLE
Use popover to display and select sensors

### ISSUE THREAD

**Issue by fossfreedom** [tarkah/budgie-cputemp-applet#4]
Suggestion.

From a newbie point of view it wasn't obvious that you had to select a sensor in budgie applet settings. Myself and another were clicking on the panel applet wondering why the temperature was zero.

As a future enhancement, suggest display all found sensors in a scroll able list in a popover together with the temperature.

If a user opens the popover and clicks on a sensor, that is the primary sensor temperature to display in the panel.

**Comment by tarkah** [comment]
Yeah this is a great idea and something I thought of as well. I'll look into this!

**Comment by fossfreedom** [comment]
Cheers - much appreciated.

FYI Testing announcement for Ubuntu Budgie here https://discourse.ubuntubudgie.org/t/testing-21-10-are-you-brave-enough/4897/11?u=fossfreedom

**Comment by tarkah** [comment]
@fossfreedom That's so cool, thank you!

An FYI, all settings are just going to be moved to the popover to keep things simple and in one place. I'll release this as 1.2.0 sometime today.

![image](https://user-images.githubusercontent.com/10239377/122982855-3847b500-d350-11eb-8ef9-5591442ffe25.png)
